name: Assign reviewer

on:
  pull_request_target: # Default: ['opened', 'synchronize', 'reopened']
    types: ["opened", "synchronize", "reopened", "ready_for_review"]

jobs:
  assign:
    runs-on: ubuntu-latest
    if: github.event.pull_request.assignee == null

    steps:
      - name: Assign reviewer
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
