name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update changelog
        uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in files
        uses: jacobtomlinson/gha-find-replace@master
        with:
          include: 'pyproject.toml'
          find: 'version = "[0-9]+.[0-9]+.[0-9]+"'
          replace: 'version = "${{ steps.release-drafter.outputs.tag_name }}"'

      - name: Commit updates
        env:
          SNAKEBIDS_VERSION: ${{ steps.release-drafter.outputs.tag_name }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Bump version to $SNAKEBIDS_VERSION" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          tags: false
